import React, { useEffect, useState, useContext } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../services/api';
import { AuthContext } from '../context/AuthContext';
import Sidebar from '../components/Sidebar';
import Header from '../components/Header';
import EmptyState from '../components/EmptyState';

export default function Reports() {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [downloading, setDownloading] = useState(false);
  const { logout } = useContext(AuthContext);
  const navigate = useNavigate();

  const fetchSummary = async () => {
    setLoading(true);
    setError('');
    try {
      const response = await api.get('/api/reports/summary');
      setSummary(response.data);
    } catch (err) {
      console.error(err);
      if (err.response?.status === 401) {
        logout();
      } else {
        setError('Failed to retrieve reporting statistics.');
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSummary();
  }, []);

  // Secure CSV download helper utilizing JWT
  const downloadReportCsv = async (endpoint, fileName) => {
    setDownloading(true);
    setError('');
    try {
      const response = await api.get(endpoint, {
        responseType: 'blob' // Essential for receiving CSV binary/text stream
      });

      // Create local temporary URL from blob
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', fileName);
      document.body.appendChild(link);
      link.click();
      
      // Clean up DOM and URL resources
      link.parentNode.removeChild(link);
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Report download failed", err);
      setError('Failed to download report. Please check server logs.');
    } finally {
      setDownloading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const formatUSD = (cents) => {
    if (cents === undefined || cents === null) return '$0.00';
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100);
  };

  if (loading) {
    return (
      <div className="app-container">
        <Sidebar />
        <div className="main-wrapper">
          <Header title="Reports" />
          <div className="content-body" style={{ justifyContent: 'center', alignItems: 'center' }}>
            <div style={{ fontWeight: '500', color: 'var(--text-secondary)' }}>Loading report engine...</div>
          </div>
        </div>
      </div>
    );
  }

  const hasData = summary && summary.totalTransactions > 0;

  return (
    <div className="app-container">
      <Sidebar />
      <div className="main-wrapper">
        <Header title="Report Center" />

        <div className="content-body">
          {error && <div className="alert alert-danger">{error}</div>}

          {!hasData ? (
            <EmptyState 
              title="No regional statistics available." 
              description="Import transaction data to generate reports."
              actionText="Import Data"
              onAction={() => navigate('/transactions')}
            />
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '30px' }}>
              {/* Export Panel */}
              <div className="card">
                <h3 className="card-title">Available Corporate Exports</h3>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '20px' }}>
                  
                  {/* Regional Report card */}
                  <div style={{ border: '1px solid var(--border-color)', padding: '20px', borderRadius: 'var(--border-radius)', display: 'flex', flexDirection: 'column', gap: '15px' }}>
                    <div style={{ fontSize: '1rem', fontWeight: '600' }}>Regional Category Report</div>
                    <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', flexGrow: 1 }}>
                      Rolls up total revenue generated by product category across all geographic territories.
                    </p>
                    <button 
                      className="btn btn-secondary" 
                      onClick={() => downloadReportCsv('/api/reports/regional/csv', 'regional_sales_report.csv')}
                      disabled={downloading}
                    >
                      💾 Export to CSV
                    </button>
                  </div>

                  {/* Category Report card */}
                  <div style={{ border: '1px solid var(--border-color)', padding: '20px', borderRadius: 'var(--border-radius)', display: 'flex', flexDirection: 'column', gap: '15px' }}>
                    <div style={{ fontSize: '1rem', fontWeight: '600' }}>Category Aggregation Report</div>
                    <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', flexGrow: 1 }}>
                      Ranks product categories by global turnover, summarizing general market interest.
                    </p>
                    <button 
                      className="btn btn-secondary" 
                      onClick={() => downloadReportCsv('/api/reports/category/csv', 'category_sales_report.csv')}
                      disabled={downloading}
                    >
                      💾 Export to CSV
                    </button>
                  </div>

                  {/* Executive Summary card */}
                  <div style={{ border: '1px solid var(--border-color)', padding: '20px', borderRadius: 'var(--border-radius)', display: 'flex', flexDirection: 'column', gap: '15px' }}>
                    <div style={{ fontSize: '1rem', fontWeight: '600' }}>Executive Performance Summary</div>
                    <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', flexGrow: 1 }}>
                      Brief summary sheet containing all major KPIs, boundaries, and best performing regions.
                    </p>
                    <div style={{ display: 'flex', gap: '10px' }}>
                      <button 
                        className="btn btn-secondary" 
                        style={{ flex: 1 }}
                        onClick={() => downloadReportCsv('/api/reports/executive/csv', 'executive_summary_report.csv')}
                        disabled={downloading}
                      >
                        💾 Export CSV
                      </button>
                      <button 
                        className="btn btn-primary" 
                        style={{ flex: 1 }}
                        onClick={handlePrint}
                      >
                        🖨️ Print Report
                      </button>
                    </div>
                  </div>

                </div>
              </div>

              {/* Printable Dashboard Preview */}
              <div className="card printable-area">
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', borderBottom: '2px solid var(--text-primary)', paddingBottom: '10px' }}>
                  <div>
                    <h3 style={{ fontSize: '1.25rem', fontWeight: '700' }}>SalesSphere BI - Executive Performance Report</h3>
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginTop: '4px' }}>
                      Generated at: {new Date().toLocaleString()} | Latest Import: {summary.latestImportTime || 'N/A'}
                    </div>
                  </div>
                  <span style={{ fontWeight: '800', color: 'var(--primary-btn)', fontSize: '1.1rem' }}>CONFIDENTIAL</span>
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '15px', marginBottom: '30px' }}>
                  <div style={{ border: '1px solid var(--border-color)', padding: '15px', borderRadius: 'var(--border-radius)' }}>
                    <div style={{ fontSize: '0.75rem', fontWeight: '600', textTransform: 'uppercase', color: 'var(--text-secondary)' }}>Total Corporate Revenue</div>
                    <div style={{ fontSize: '1.5rem', fontWeight: '700', marginTop: '5px' }}>{formatUSD(summary.totalRevenue)}</div>
                  </div>
                  <div style={{ border: '1px solid var(--border-color)', padding: '15px', borderRadius: 'var(--border-radius)' }}>
                    <div style={{ fontSize: '0.75rem', fontWeight: '600', textTransform: 'uppercase', color: 'var(--text-secondary)' }}>Total Processed Transactions</div>
                    <div style={{ fontSize: '1.5rem', fontWeight: '700', marginTop: '5px' }}>{summary.totalTransactions.toLocaleString()}</div>
                  </div>
                  <div style={{ border: '1px solid var(--border-color)', padding: '15px', borderRadius: 'var(--border-radius)' }}>
                    <div style={{ fontSize: '0.75rem', fontWeight: '600', textTransform: 'uppercase', color: 'var(--text-secondary)' }}>Leading Sales Territory</div>
                    <div style={{ fontSize: '1.5rem', fontWeight: '700', marginTop: '5px' }}>{summary.topRegionName || 'N/A'}</div>
                  </div>
                </div>

                <h4 style={{ fontSize: '0.95rem', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '15px', borderBottom: '1px solid var(--border-color)', paddingBottom: '5px' }}>Regional Category breakdown</h4>
                <table className="corporate-table" style={{ border: '1px solid var(--border-color)', fontSize: '0.85rem' }}>
                  <thead>
                    <tr>
                      <th>Region</th>
                      <th>Category</th>
                      <th style={{ textAlign: 'right' }}>Total Revenue (USD)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(summary.regionCategorySales).flatMap(([region, categories]) => {
                      const catEntries = Object.entries(categories);
                      return catEntries.map(([category, amount], idx) => (
                        <tr key={`${region}-${category}`}>
                          {idx === 0 ? (
                            <td 
                              rowSpan={catEntries.length} 
                              style={{ fontWeight: '600', borderRight: '1px solid var(--border-color)', verticalAlign: 'top' }}
                            >
                              {region}
                            </td>
                          ) : null}
                          <td>{category}</td>
                          <td style={{ textAlign: 'right', fontWeight: '500' }}>{formatUSD(amount)}</td>
                        </tr>
                      ));
                    })}
                  </tbody>
                </table>
              </div>

            </div>
          )}
        </div>
      </div>
    </div>
  );
}
